name: Docker
on:
  push:
    tags:
      - '*'
  schedule:
    # twice a month
    - cron: '20 8 5,20 * *'
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  ndn6-tools:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn6-tools
      target: ndn6-tools
