name: Docker
on:
  push:
    tags:
      - '*'
  schedule:
    # monthly on day 5
    - cron: '20 10 5 * *'
  workflow_dispatch:

permissions:
  artifact-metadata: write
  attestations: write
  id-token: write
  packages: write

jobs:
  ndn6-tools:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn6-tools
